name: Beta lints

# We only run these lints on trial-merges of PRs to reduce noise.
on: pull_request

permissions:
  contents: read

jobs:
  clippy-beta:
    name: Clippy (beta)
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8 # beta
        id: toolchain
        with:
          toolchain: beta
          components: clippy
      - run: rustup override set "${TOOLCHAIN}"
        shell: sh
        env:
          TOOLCHAIN: ${{steps.toolchain.outputs.name}}
      - name: Run Clippy (beta)
        run: cargo clippy --all-features --all-targets -- -W clippy::all
