name: Beta lints

# We only run these lints on trial-merges of PRs to reduce noise.
on: pull_request

permissions:
  contents: read

jobs:
  clippy-beta:
    name: Clippy (beta)
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - uses: dtolnay/rust-toolchain@4214355880fc9d71f45c3396ca2d59d3c7850f3f # beta
        id: toolchain
        with:
          toolchain: beta
          components: clippy
      - run: rustup override set "${TOOLCHAIN}"
        shell: sh
        env:
          TOOLCHAIN: ${{steps.toolchain.outputs.name}}
      - name: Run Clippy (beta)
        run: cargo clippy --all-features --all-targets -- -W clippy::all
